#baseurl: ""
#url: ""

remote_theme: Sylhare/Type-on-Strap

theme_settings:
  title: Use Ramda with React and Redux
  avatar: assets/img/triangle.svg
  description: Patterns and techniques for Ramda and React with Ramda library
  github: tommmyy
  google_fonts: Source+Sans+Pro:400,700,700italic,400italic

title: React and Ramda patterns
kramdown:
  parse_block_html: true
